# Generated by Django 5.1.5 on 2025-02-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesstore', '0002_alter_cartitem_movie_alter_orderitem_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
