# Generated by Django 5.1.5 on 2025-02-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesstore', '0003_remove_orderitem_order_remove_orderitem_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]